<div id = "sidenav"> 
			<h4>Lab Assignment</h4>
			<ul>
  				<li><a href="http://helios.vse.gmu.edu/~ashafin/IT207/LAB1/LAB1.php" style="color: white;"> Assignment 1 </a></li>
    			<li><a href="http://helios.vse.gmu.edu/~ashafin/IT207/LAB2/index.php" style="color: white;"> Assignment 2 </a></li>
    			<li><a href="www.google.com" style="color: white;"> Assignment 3 </a></li>
    			<li><a href="www.google.com" style="color: white;"> Assignment 4 </a></li>
			</ul>  
			<br/>
			<h4>Lab Practice</h4>
			<ul>
  				<li><a href="http://helios.vse.gmu.edu/~ashafin/IT207/practicum1/page1.php" style="color: white;"> Practicum 1 </a></li>
  				<li><a href="www.google.com" style="color: white;"> Practicum 2 </a></li>	
			</ul>  
</div>